In [45]:
import numpy as np
def LU_factorizacion(A):
    n = A.shape[0]  # Número de filas (o columnas) de la matriz A
    U = A.copy()  # Crear una copia de A para U
    L = np.eye(n)  # Inicializar L como una matriz identidad de nxn

    # Proceso de factorización LU
    for k in range(n - 1):  # Iterar sobre cada columna excepto la última
        for i in range(k + 1, n):  # Iterar sobre cada fila por debajo del pivote actual
            L[i, k] = U[i, k] / U[k, k]  # Calcular el multiplicador y asignarlo a L
            U[i, k:] = U[i, k:] - L[i, k] * U[k, k:]  # Actualizar la fila i de U restando el múltiplo de la fila k

    return L, U  # Devolver las matrices L y U

def Cholesky_LL(L, U):
    n = L.shape[0]

    # Crear una matriz diagonal D a partir de U
    D = np.zeros((n, n), dtype=float)
    for i in range(n):
        D[i, i] = U[i, i]

    L_chol = L @ np.sqrt(D)

    return L_chol, L_chol.T

def Cholesky_LDL(L, U):
    n = L.shape[0]

    # Crear una matriz diagonal D a partir de U
    D = np.zeros((n, n), dtype=float)
    for i in range(n):
        D[i, i] = U[i, i]

    return L,D, L.T

##A

In [58]:
A=np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])

In [59]:
L1,U1=LU_factorizacion(A)
L1@U1

array([[ 2. , -1. ,  0. ],
       [-1. ,  1.5, -1. ],
       [ 0. , -1. ,  2. ]])

###a)

In [43]:
L11,L11t=Cholesky_LL(L1,U1)
L1@L11t

array([[ 1.41421356, -0.70710678,  0.        ],
       [-0.70710678,  1.35355339, -1.        ],
       [ 0.        , -1.        ,  2.        ]])

### b)

In [44]:
L12,D12,L12t=Cholesky_LDL(L1,U1)
L12@D12@L12t

array([[ 2. , -1. ,  0. ],
       [-1. ,  1.5, -1. ],
       [ 0. , -1. ,  2. ]])